requirements.txt
src/config.yaml
src/core/utils/win32/media.py
src/core/validation/widgets/yasb/media.py
src/core/widgets/yasb/media.py
src/main.py
src/styles.css

Adds a media widget that shows the currently playing media as pulled from the Windows API. In addition, it features media buttons (previous/next track and play/pause). Provides some options for shortening fields with ellipsis to prevent the bar from blowing up from the occasional large title/artist field. Media thumbnail is used as a semi-transparent background.
For those who want it to take up little space in the bar, you can also disable the text/thumbnail field in the config and just have the media control buttons instead.
Still needs some work on the styling. Depending on the thumbnail, text might not be as legible. You can mitigate this with the background transparency, but I'd rather have something like text shadow to help improve legibility across thumbnails. 
Known issue: Border …

Add Media Widget

---

src/core/utils/win32/media.py
src/core/widgets/yasb/media.py

Hopefully this solves weird behaviour where the media detection freezes until restart. The code with dynamic size introduced another stream open, but we never close them. Now we only use a single stream call, and always close it.
Also fixes a small thumbnail loading bug:
- Fixes small bug where if you close a media player playing a certain song, and reopen it and continue, the thumbnail does not load because the title and artist are the same. Now, if media info is ever None, it wipes the last title and artist used for thumbnail detect.

bugfix(media): winsdk stream stability

---

src/core/widgets/yasb/battery.py
src/core/widgets/yasb/memory.py
src/styles.css

Small changes that allow you to set value-dependent colors for the icons of the power and memory widget. Most of the code to make this happen was still left (as well as all parameters in the schema), but the CSS properties were missing. Added the property setting in code and added disabled template CSS code for the colors. The template colors should be consistent with the rest of the bar (Catppuccin Mocha).

feat(power/mem): Reintroduce value-dependent icon color

---

src/config.yaml
src/core/bar_manager.py
src/core/validation/widgets/yasb/media.py
src/core/widgets/yasb/media.py
src/styles.css

Implements a corner rounding procedure for the media thumbnail. This cannot be achieved by CSS, so we need to make the corners transparent to mimic round corners. Using `thumbnail_corner_radius` users can set the rounding to match their CSS settings, or set it to 0 for default square corners.
In addition, provides a few small refactors and cleanups.

feat(media): Rounded thumbnail corners

---

src/core/bar_manager.py
src/core/utils/utilities.py
src/core/utils/win32/media.py
src/core/widgets/yasb/media.py

This PR provides a total rewrite for much of the backend of the media widget, now using event-based  instead of timer-base updates. Multiple users have experienced high cpu uasge, NPSMSvc crashes, and other odd behaviour. This was likely caused by the bar spamming the service with update requests. Especially when multiple bars were present (multiple monitors), the amount of requests was large since each widget would do its own requests for updating.
The current implementation subscribes update functions to the `winsdk` events, and updates from there. The wrapper for `winsdk` media handling is a singleton to which all media widgets subscribe, meaning that it only makes one windows api call(back) no matter how many widgets.
Remaining known issues: Updates slow on Firefox, which seems to be …

feat(media): Event-based updating

---

src/config.yaml
src/core/bar_manager.py
src/core/utils/utilities.py
src/core/validation/widgets/yasb/media.py
src/core/widgets/yasb/media.py

Fixes a bug where the bar crashes on config reload if the media widget is not enabled. This was caused by the bar initializing a new media manager in the shutdown loop because it was not made by any of the widgets. Fixed by only trying to stop it if an instance exists.
Also removes the now unused update_interval parameter from the config and schema, since we are now using event-based updates.

fix(media): Fix error on config change

---

src/config.yaml
src/core/validation/widgets/yasb/wifi.py
src/core/widgets/yasb/wifi.py
src/styles.css

Adds the ability to show an ethernet connection icon when connected to ethernet, instead of showing 'no wifi' icon. Since `netsh` seems to give problems for the lan interfaces, I use the winsdk to identify whether the current connection is WiFi or not. If it is WiFi or disconnected, it uses the `netsh` code, otherwise sets an Ethernet icon.
I did switch to Segoe Fluent Icons because I could not get the NerdFont icons to look nice for the ethernet one. If we want the icons to stay the same, we'd need to look a bit deeper into it.

feat(wifi): Add Ethernet connection icon

---

README.md
src/core/widgets/base.py
src/core/widgets/yasb/custom.py

Added a section to use yasb with the installer given in the releases.

update(readme): added extra options to how to run section.

---

src/core/widgets/yasb/memory.py

This adds a "virtual_mem_used" to show the system ram usage and "virtual_mem_outof" to show a system ram usage / total system ram.
Would be nice to also change the default ram widget config (assuming this pr gets merged) to "virtual_mem_used" as I feel like the average user would like to see their ram usage instead of how much ram is free. (if you feel like this should be changed, lmk and I'll commit a change to config.yaml)

Add more RAM usage widget config

---

docs/widgets/(Widget)-Wallpapers.md

Adding "Using pywal with wallpapers" section to the Wallpaper Widget Docs.
1. Added a basic installation guide for pywal
2. Added a usage section, detailing on how to use pywal (redirecting to official docs for template and basic usage of commands/flags)
3. In the usage section there is a 3 step proposal on how to use pywal with YASB - powershell script, "@import function", making the whole style.css a template for pywal.
4. Added a section outlining how to use and install different backends.

Adding pywal section to Wallpaper Widget Docs

---

README.md
docs/_Sidebar.md
docs/widgets/(Widget)-Libre-HW-Monitor.md
src/build.py
src/config.yaml
src/core/validation/widgets/yasb/libre_monitor.py
src/core/widgets/yasb/libre_monitor.py
src/styles.css

Adds the [Libre Hardware Monitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor) (LHM) widget that connects to the local LHM web server and requests the selected sensor data using `SensorId` string.
SensorId can be found in http://localhost:8085/data.json when the LHM server is running.
Can display current value, min, max, unit and histogram.
Value unit is also received from the LHM so `{info[value]} {info[unit]}` will display 52 °C.
Only the specific sensor data is requested.
The post request is done asynchronously using QNetworkAccessManager to avoid locking the UI.
`update_interval` is limited to the LHM update interval.
Min and max values are not possible to get from the LHM, so they are calculated from the history. History size is also adjustable in the config. History …

feat(widget): Libre Hardware Monitor Widget

---

docs/widgets/(Widget)-Libre-HW-Monitor.md
src/core/validation/widgets/yasb/libre_monitor.py
src/core/widgets/yasb/libre_monitor.py

Added optional customizable error labels for **invalid sensor id**, **connection error** and **authentication error** situations:
- **sensor_id_error_label** optional config option is added
- **connection_error_label** optional config option is added
- **auth_error_label** optional config option is added.
Changed default error labels to be more concise for invalid sensor id and authentication failed to "N/A" and "Auth Failed...".
Moved request creation to \_\_init\_\_.
Updated docs.

feat(LHM): Customizable error labels for LibreHardwareMonitor Widget

---

src/core/widgets/yasb/libre_monitor.py

SensorID string will now be properly URL encoded.
This should ensure that the request URL is correct even if SensorID string has special characters in it.

fix(LHM): proper SensorID string encoding for request URL.

---

docs/widgets/(Widget)-Language.md
src/core/widgets/yasb/language.py

Implements a `layout_name` variable accessible via `{lang[layout_name]}` in the Language widget.
Closes #90. 
This config:
```yml
widgets:
language:
type: 'yasb.language.LanguageWidget'
options:
label: "<span>\uf11c</span>{lang[language_code]}-{lang[country_code]}  {lang[layout_name]}"
```
will give this:

Add support for using keyboard layout in Language widget

---

docs/_Sidebar.md
docs/widgets/(Widget)-GlazeWM-Workspaces.md

Forgot to add sidebar links for GlazeWM wiki pages and also fixed some typos and incorrect placeholders.

docs(widget/glazewm): Added wiki sidebar links

---

src/core/widgets/glazewm/workspaces.py

The brief window popup during YASB startup was fixed.
It was a "setVisible(True)" call that was made before the "GlazeWM Offline" label was added to the layout that caused this.
Also tidied up some visibility logic for glazewm offline label.

fix(widget/glazewm): brief window popup fixed

---

src/core/widgets/yasb/taskbar.py

This pull request changes taskbar icon rendering so it will look to all open programs and render all icons except the windows that won't show neither on alt-tab nor task manager (it does so by checking for `WS_EX_NOREDIRECTIONBITMAP` style, which is not included on `win32con`).
It also fixes some typing and changes some checks.
With this pull request, all taskbar icons will show even if you start yasb after a bunch of programs are opened before.

Fixed taskbar not showing all apps icons

---

README.md
docs/_Sidebar.md
docs/widgets/(Widget)-Systray.md
src/core/tray.py
src/core/utils/systray/systray_widget.py
src/core/utils/systray/tray_monitor.py
src/core/utils/systray/utils.py
src/core/utils/systray/win_types.py
src/core/utils/systray/win_wrappers.py
src/core/validation/widgets/yasb/systray.py
src/core/widgets/yasb/systray.py

A system tray widget that works similar to the original Windows systray.
**Functionality:**
- Shows the system tray icons that can be pinned into a separate container and the unpinned icons can be hidden using the collapse toggle button (by default on the left of the widget).
- Pinning can be done in two ways:
- by holding a modifier key (alt by default) + LMB click.
- by dragging and dropping the icon to the pinned container.
- Icons can be repositioned by dragging and dropping.
- Icons positions and pinned/unpinned state will be saved automatically and restored on the next YASB launch.
- If system tray widget is added to multiple monitors - each monitor will have its separate icon position and pinned/unpinned saved state. It's NOT shared between systray widgets.
**Known limitations:**
- …

feat(systray): added systray widget

---

src/core/utils/systray/tray_monitor.py

Changes the systray window to "WS_DISABLED" and size to 0 for it to be ignored by tiling managers and have better compatibility with Buttery Taskbar app. This will still show a small window at the top-left, but it is less noticeable.

fix(systray): Buttery Taskbar compat fix

---

src/core/utils/win32/app_icons.py

This PR attempts to draw taskbar and active window icons using the same method as systray. It vastly improves icons quality and solves problems rendering icons of some apps (e.g. 7-zip).
Probably needs testing with HiDPI / different scaling.
Before:
After:

Improved taskbar and active_window icon rendering

---

src/core/utils/systray/systray_widget.py

Fixes the additional left click sent when triggering a double click event. For example Steam was opening the drop-down menu on double click because of the extra click sent. Now double click should behave as expected.

fix(systray): improved double click handling for systray icons

---

docs/widgets/(Widget)-Systray.md
src/core/widgets/yasb/systray.py

Systray expand/collapse button now has a right click menu to refresh the systray icons.
This allows to send a "TaskbarCreated" message to Windows without restarting YASB.
**Mostly a debug option**, but might be useful if for some reason some icons got stuck or not added.
Might be removed in the future when systray widget is more robust.
https://github.com/user-attachments/assets/5ccd840b-36e2-43ce-89b8-732e046863cf

feat(systray): systray expand/collapse right click menu

---

docs/widgets/(Widget)-WiFi.md

Add missing info about the `ethernet_icon`.
Source: https://github.com/amnweb/yasb/blob/393054dc1db199c516e10800076e92eb98a58f09/src/core/validation/widgets/yasb/wifi.py#L17
While at it, also update the signal strength info.
Source:
https://github.com/amnweb/yasb/blob/393054dc1db199c516e10800076e92eb98a58f09/src/core/validation/widgets/yasb/wifi.py#L12

docs: update wifi widget wiki

---

docs/widgets/(Widget)-Volume.md
src/core/validation/widgets/yasb/volume.py
src/core/widgets/yasb/volume.py

Hey there!
Currently, whenever you mute your device, the `{level}` in the volume widget display the text `"mute"`. This value is hardocoded ([link](https://github.com/amnweb/yasb/blob/9004938cd28d16f7f274ffdb8b2262698d6df981/src/core/widgets/yasb/volume.py#L481)).
With this PR I want to allow users to customize that text. I did this by creating a new config option `mute_text`. This option is not required and defaults to `"mute"`, so there will be no breaking change.
Let me know what you think :)

feat(volume): allow customizing muted volume text

---

docs/CLI.md
src/core/utils/cli.py

Hi,
First of all, huge thanks for creating the cli. I would never expect for a status bar on windows to have one and I'm amazed at how useful it is. I use `yasbc` mostly to `start`, `stop` and `reload` the bar in my glazewm config. Especially the `reload` command I find very useful, since chaining `taskkill /f /im yasb.exe` and `yasb.exe` on glazewm reload doesn't work as expected. Hovewer, since all commands have print messages, everytime they get called from glazewm, a terminal window spawns and dissappears. 
To remove that behavior I'd like to propose the `--silent` option. When passed, commands `start`, `stop` and `reload` will not print any messages, unless they come from the `stop_or_reload_application` method.
Usage:
```
yasbc start -s
```
```
yasbc reload --silent
```

feat(cli): add `--silent` option

---

docs/widgets/(Widget)-WiFi.md
src/core/widgets/yasb/wifi.py

Many popular Linux bars have the option to display the local IP address in their network widgets (e.g. [i3status](https://i3wm.org/docs/i3status.html#_ethernet) and [waybar](https://github.com/Alexays/Waybar/wiki/Module:-Network#format-replacements)). I liked that feature so I implemented it for YASB as well.
I also updated the wifi wiki to list all available replacements for labels. It's currently put in the Note, but I can make a new table similar to how [waybar](https://github.com/Alexays/Waybar/wiki/Module:-Network#format-replacements) has it, if you want.

feat(wifi): add `{ip_addr}` as a replacement option in labels

---

src/core/utils/systray/tray_monitor.py
src/core/widgets/yasb/systray.py

Some changes to the initialization logic that should be more reliable. The "TaskbarCreated" timer starts only when the SystrayMonitor thread is started, not when the Systray widget is initialized.
Also some minor refactors.

fix(systray): better initialization

---

docs/widgets/(Widget)-Custom.md
docs/widgets/(Widget)-WiFi.md
src/core/validation/widgets/yasb/wifi.py
src/core/widgets/yasb/wifi.py

Added `ethernet_label` and `ethernet_label_alt` to be displayed during active Ethernet connection. The widget text switches between `label` and `ethernet_label` as soon as the change in internet connection is detected. The alternative widget state during the switch is maintained.

feat(wifi): add ethernet_label and ethernet_label_alt

---

src/core/utils/utilities.py

This fix prevents the widget from being split between monitors if the widget button is on the edge between two adjacent monitors.
Before:
After:

fix(notes): ensure widget is fully shown on one screen

---

src/core/widgets/yasb/media.py

This avoids buttons "snapping in place" after the widget is shown.
Before:
https://github.com/user-attachments/assets/9aa0584e-7a10-4ec3-b526-f816f78c3cbd
After:
https://github.com/user-attachments/assets/8728667f-2c93-46f7-a0c4-413083e5fd07

Update media popup buttons before the widget is shown

---

src/core/utils/css_processor.py
src/main.py

The debug mode was not working because the app instance was initialized in the CSSProcessor first, instead of the main where it would. Moved the app init to be the first thing and removed the unnecessary CSSProcessor check (as app should exist there already in all cases).

fix(app): fix app instance init for debug mode

---

src/core/log.py

Some additional log formatting tweaks to add better colors for debug and formatting of the levelname

feat(log): better colors and formatting for log messages

---

docs/widgets/(Widget)-Battery.md
src/core/validation/widgets/yasb/battery.py
src/core/widgets/yasb/battery.py

Feature requested in #239
Added new option to the Battery widget. The option `hide_unsupported` defaults to true. If the system cannot provide any battery info and the `hide_unsupported` option is set to true then it will hide the Battery widget.

feat(battery): Add `hide_unsupported` option

---

README.md
docs/_Sidebar.md
docs/widgets/(Widget)-Komorebi-Stack.md
src/build.py
src/core/event_enums.py
src/core/utils/komorebi/client.py
src/core/validation/widgets/komorebi/stack.py
src/core/widgets/komorebi/stack.py

This widget allows users to see all windows in the currently active stack and click to focus on any individual window.
I have tested every action I know and can perform, including stacking, unstacking, and switching workspaces, and the buttons update correctly.
I haven't tested actions across monitors yet, but there shouldn't be any issues.
Known issue: 
When using the taskbar or a taskbar widget to open a window that is part of a stack but not currently focused, the widget may not detect the change and fail to update the buttons. This might occur because the taskbar only brings a single window to the front, rather than the entire stack.
https://github.com/user-attachments/assets/cbd4bf70-4353-4812-94ac-7beabdab08dd

feat(komorebi): Stack Widget

---

docs/widgets/(Widget)-GlazeWM-Workspaces.md
src/core/validation/widgets/glazewm/workspaces.py
src/core/widgets/glazewm/workspaces.py

Implements feature requested in #137 .

feat(glazewm_workspaces): add `active label`

---

docs/widgets/(Widget)-Github.md
src/core/validation/widgets/yasb/github.py
src/core/widgets/yasb/github.py

This option will show a small dot in a specified corner with specified color when there are unread notifications available. 
Can also have customizable x and y margin. 
It is drawn on the QLabel itself, so changing margin/padding for the `.icon` style will affect the dot position.
```yaml
notification_dot:
enabled: True
corner: "bottom_left" # Can be "top_left", "top_right", "bottom_left", "bottom_right"
color: "red" # Can be hex color or string
margin: [ 1, 1 ] # x and y margin for the dot
```

feat(github): added notification dot option

---

docs/widgets/(Widget)-GlazeWM-Workspaces.md
src/core/widgets/glazewm/workspaces.py

PR #249 added labels `active_populated` and `active_empty`, however the CSS classes for them for not implemented. This PR adds missing classes, removes obsolete ones and updates the docs.
BREAKING CHANGE: replace `.glazewm-workspaces .ws-btn.active` with `.glazewm-workspaces .ws-btn.active_populated` in styles.css

feat(glazewm)!: add css classes `active_populated` and `active_empty`

---

docs/widgets/(Widget)-Komorebi-Stack.md
src/core/utils/komorebi/client.py
src/core/validation/widgets/komorebi/stack.py
src/core/widgets/komorebi/stack.py

What I did:
- Added app icons 
- Change button structures from `QPushButton` to `QFrame + QHBoxLayout` for better label/icon styling
- Introduced options: `max_length_overall`, `show_icon`, `icon_size`, `hide_if_no_stack` (from #250) 
- Removed `show_only_stack` to reduce redundancy
- Applied `label_shadow` with label and icon

feat(komorebi): add app icons/more options to stack widget

---

src/core/utils/utilities.py

Fixed an issue where main bar padding affected the popup widget position when `windows_app_bar` was set to `true`.
Instead of using `screen.availableGeometry()` we just get the `screen.geometry()`

fix(popup_widget): fixed padding not being ignored issue

---

docs/Configuration.md

Fixes a typoo in the configuration docs.

docs(config): fix `api_ley` typoo

---

docs/widgets/(Widget)-Komorebi-Workspaces.md
src/core/utils/komorebi/client.py
src/core/validation/widgets/komorebi/workspaces.py
src/core/widgets/komorebi/workspaces.py

Added a new button class `WorkspaceButtonWithIcons` to display opened app icons in each workspace, along with a new option:
```yaml
app_icons: 
enabled: true
enabled_active: true
size: 12
max_icons: 0
hide_duplicates: false
hide_floating: true
```
- This new class uses `QFrame + QHBoxLayout` (similar to the stack widget button), applying styling via `.ws-btn .label` and `.ws-btn .icon`.
- The original button class is left completely untouched to preserve compatibility. The new class is only used when app icons are enabled, ensuring that existing themes won’t break after the update.
- Users who want to style the new icon-enabled buttons will need to update their custom CSS accordingly.

feat(komorebi): display opened app icons per workspace

---

docs/widgets/(Widget)-Weather.md
src/core/validation/widgets/yasb/weather.py
src/core/widgets/yasb/weather.py

This one will break configs, but I noticed that the icons were not showing properly (https://github.com/amnweb/yasb/discussions/272) and since we are fixing the typo here (#274) I figured it's a good time to extend the icons a bit. Issue mentioned might be because of the weather API changes and how we parsed the string before:
```py
icon_string = f"{conditions_data[0].lower() + conditions_data[1:]}{'Day' if current['is_day'] == 1 else 'Night'}".strip()
```
Now it's all based on codes and nothing else.
Changelog:
- Fixes the issue where the icon mapping was not correct for some weather conditions.
- Adds a new icon mapping for the weather widget.
- Changes the weather text for `condition_text`.
- Changes the "is_day" from int to "Day/Night" string.
- Fixes a small issue with the signal …

feat(weather_widget): weather widget icon mapping improvements

---

docs/widgets/(Widget)-WiFi.md
src/core/validation/widgets/yasb/wifi.py
src/core/widgets/yasb/wifi.py

This PR adds an option called `hide_if_ethernet` so if the PC or Laptop is connected to ethernet than the user can determine if they want to hide the widget or not.

feat(wifi): add `hide_if_ethernet` option

---

docs/widgets/(Widget)-Bluetooth.md
src/core/validation/widgets/yasb/bluetooth.py
src/core/widgets/yasb/bluetooth.py

**Added options:**
- **label_no_device:** The string to display `{device_name}` when no devices are connected.
- **label_device_separator:** The string to separate multiple device names.
- **max_length:** The maximum number of characters of the label text. If the text exceeds this length, it will be truncated.
- **max_length_ellipsis:** The string to append to truncated label text.
- **device_aliases:** A list of dictionaries specifying device aliases. Each dictionary should contain a `name` and an `alias`. The `name` is the real name of the device, and the `alias` is the text to display for that device.

feat(bluetooth): add more label options

---

docs/widgets/(Widget)-GlazeWM-Binding-Mode.md
src/core/utils/glazewm/client.py
src/core/validation/widgets/glazewm/binding_mode.py
src/core/widgets/glazewm/binding_mode.py

This PR implements multiple new features to improve the usage of the binding mode widget.
- new callbacks `next_binding_mode` and `prev_binding_mode`, with these the user can cycle through workspaces in order that is given in the `binding_modes_to_cycle_through` option.  Example for the  `binding_modes_to_cycle_through` option: `['none', 'resize', 'pause']`
- `icons` option enables user to specify an icon for each binding mode based on the name of the mode.
- example `{'pause' : '\uf28c'}`
- `default_icon` option is used for the modes where the user didn't specify an icon
- added class to handle offline labels
- added classes for each of the different mode icons specified

feat(glazewm_binding_mode): cycling through modes, `default_icon` option, `icons` option, improved css classes

---

src/core/utils/systray/tasks_service.py
src/core/utils/systray/tray_monitor.py
src/core/utils/systray/utils.py
src/core/utils/win32/bindings.py
src/core/utils/win32/media.py
src/core/widgets/yasb/systray.py

Fixes .NET app crashes caused by apps not being able to call the real systray functions and get a proper success/handled response.
- Added a new thread and service to handle taskbar messages
- Real systray handle is now cached
- Abstracted the win32 window creation into `NativeWindowEx`
- `bindings.py` cleanup
- Logging cleanup
- Improved `get_exe_path_from_hwnd` error handling
- Removed even more unnecessary `media.py` logging spam

fix(systray): fix .NET app crash

---

src/core/utils/glazewm/client.py
src/core/widgets/glazewm/workspaces.py

Improves the workspace scrolling feature with the new `--prev-active-workspace-on-monitor` and `--next-active-workspace-on-monitor` commands for a cleaner solution.
> [!CAUTION]
> Latest GlazeWM version is required.

feat(glazewm): improve scroll with new glazewm commands

---

docs/CLI.md
docs/widgets/(Widget)-Launchpad.md
docs/widgets/(Widget)-Power-Menu.md
docs/widgets/(Widget)-Wallpapers.md
pyproject.toml
src/cli.py
src/core/bar_manager.py
src/core/global_state.py
src/core/utils/cli_server.py
src/core/utils/controller.py
src/core/utils/launchpad/app_loader.py
src/core/utils/launchpad/icon_extractor.py
src/core/utils/win32/utilities.py
src/core/validation/widgets/yasb/launchpad.py
src/core/widgets/yasb/launchpad.py
src/core/widgets/yasb/power_menu.py
src/core/widgets/yasb/wallpapers.py

- Introduced a new CLI command `toggle-widget` to show/hide specific widgets.
- Enhanced the command with options to follow the mouse cursor or focused window.
- Updated the CLI handler to process the new command and emit events for widget management.
- Added global state management for tracking screens where bars are displayed.

feat(cli): add toggle-widget command for widget visibility control

---

docs/Configuration.md
src/config.yaml
src/core/bar_manager.py
src/core/utils/update_check.py
src/core/utils/utilities.py
src/core/validation/config.py
src/main.py

The app should automatically check for updates on startup and display a notification if a new version is available. The notification will remain visible until the user dismisses it or clicks Download & Install.
New config options `update_check` (disabled by default)

feat(update-check): implement update check service and configuration

---

docs/widgets/(Widget)-Media.md
src/core/utils/utilities.py
src/core/validation/widgets/yasb/media.py
src/core/widgets/yasb/media.py

Main changes:
- Added a new class called `ScrollingLabel` that inherits from `QLabel` and adds scrolling functionality to it.
- Added the `ScrollingLabel` based option to the `Media` widget.
- Media label truncation will be disabled if scrolling is enabled.
- Scrolling label has four styles/directions: `left`, `right`, `bounce` and `bounce-ease`
- `bounce-ease` will use easing function with parameters (`slope`, `position`, `minimum`) that can be changed in the config. Parameters can be tested here: https://www.desmos.com/calculator/j7eamemxzi
Scrolling label config:
```yaml
scrolling_label:
enabled: false
update_interval_ms: 33
style: "left"  # can be "left", "right", "bounce", "bounce-ease"
separator: " | "
label_padding: 1
ease_slope: 20
ease_pos: 0.8
ease_min: 0.5
```
Some notes:
- The …

feat(media): added scrolling label option

---

src/core/utils/utilities.py

- This avoids clipping of the text if its width is almost the same as QLabel max width.

fix(ScrollingLabel): Improve bounce width calculation

---

docs/widgets/(Widget)-CPU.md
docs/widgets/(Widget)-Disk.md
docs/widgets/(Widget)-Memory.md
src/core/validation/widgets/yasb/cpu.py
src/core/validation/widgets/yasb/disk.py
src/core/validation/widgets/yasb/memory.py
src/core/widgets/yasb/cpu.py
src/core/widgets/yasb/disk.py
src/core/widgets/yasb/memory.py

- **Added CPU thresholds**
- The CPU widget can now be programmed to change color based upon percentage used just like RAM
- **Added RAM Histogram icons**
- The RAM Widget can now have histogram icons like the CPU allowing support for Ascii Progress bars
- **Added Disk Thresholds**
- Disk Widget can now be programmed to change color based upon percentage used just like RAM
Changes Demo

Added CPU thresholds, RAM Histogram, Disk Thresholds

---

src/core/widgets/yasb/volume.py

Currently, the app can crash where no audio device is present. This also displays the "No Device" text again on missing audio device.
Commit with earlier fix:
https://github.com/amnweb/yasb/commit/da7d991255bf6fea2d9d6b4ba68f1f0399308d10 
Commit introducing the bug:
https://github.com/amnweb/yasb/commit/e8aa0581306938d95d28a4b8236c1d3fbc4c606d
Logs from crashes I have been having:
```
...
2025-08-10 21:42:22,933 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-10 21:42:22,934 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-10 21:42:22,934 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-10 21:42:23,084 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-10 …
```

fix(volume): handle mute status on absent audio device

---

src/core/utils/widgets/glazewm/client.py

Potential fix for Windows 10 GlazeWM issue where it was not sending the monitor's name properly.
Could not repro this on my Windows 10 VM though. YASB v1.8.2 worked perfectly fine with GlazeWM v3.9.1.
- If monitor name is missing, use the default placeholder instead.
- Remove warning from monitor name check.
- Fail early if monitor hwnd is not sent by GlazeWM.

fix(GlazeWM): fix monitor name check for windows 10

---

src/core/widgets/yasb/wallpapers.py

Made the timer shared across all instances of the wallpaper widget.
Fixed the bug by making _timer_running a shared state. I checked how it was done in the Pomodoro Widget to implement the fix.
Only the boolean is shared, not the timer itself, since there’s no need for more. The timer value isn’t shown to the user.
First contribution 😄

fix no shared timer in wallpaper widget #464

---

docs/widgets/(Widget)-Taskbar.md
src/core/validation/widgets/yasb/taskbar.py
src/core/widgets/yasb/taskbar.py

- Introduced `hide_empty` boolean option to control visibility of the taskbar widget when no applications are displayed.

feat(taskbar): add option to hide taskbar widget when empty
