- src/core/utils/win32/media.py
- src/core/widgets/yasb/media.py
Fixes the following issues:
- Removed fixed thumbnail buffer size in favor of flexible size (thanks to @amnweb)
- Fixed thumbnail scaling for rectangular thumbnails
- Reduce PIL log pollution (on DEBUG)
- Catch media property errors in function itself
> Media widget improvements

- src/core/widgets/yasb/weather.py
i would like to publish my dotfiles however i can't do that without leaking my location or at least general location. This just allows you to set the weather location via an environment variable
> Add weather location env option

- README.md
- docs/widgets/(Widget)-GlazeWM-Tiling-Direction.md
- docs/widgets/(Widget)-GlazeWM-Workspaces.md
- src/core/utils/glazewm/client.py
- src/core/validation/widgets/glazewm/tiling_direction.py
- src/core/validation/widgets/glazewm/workspaces.py
- src/core/widgets/glazewm/tiling_direction.py
- src/core/widgets/glazewm/workspaces.py
- Added GlazeWM Workspaces and Tiling Direction widgets.
- Updated readme and added docs.
> feat(widget/glazewm): GlazeWM support

- docs/Configuration.md
adjusted some typos in the configuration.md wiki file, very minor stuff
> fix small typos

- src/core/widgets/yasb/taskbar.py
With this PR it is possible to add extra style to foreground application using class `.app-icon.foreground`.
> Added extra class to taskbar foreground app

- src/core/widgets/yasb/systray.py
Fixed the pin state restore on initial launch.
Increased the init_timer to 5 seconds.
> fix(systray): fixed the pin state restore on initial launch

- src/core/utils/systray/tray_monitor.py
- src/core/widgets/yasb/systray.py
refactor(systray): moved thread start to after signal connections
chore(systray): cleanup some typing related comments
> fix(systray): added a delay for send_taskbar_created

- docs/Configuration.md
- requirements.txt
- src/core/config.py
- src/core/validation/config.py
- src/main.py
This pull request introduces the ability to load environment variables from a specified file.
* **Documentation update:**
- Added `env_file` option to the configuration documentation in `docs/Configuration.md`.
* **Configuration handling:**
- Updated the configuration validation schema in `src/core/validation/config.py` to include the new `env_file` option.
- Added `get_resolved_env_file_path` function in `src/core/config.py` to resolve the absolute path of the environment file.
* **Main application logic:**
- Modified the `main` function in `src/main.py` to load environment variables from the specified file if the `env_file` option is set.
> feat(config): add support for environment file loading

- docs/widgets/(Widget)-Systray.md
- src/core/validation/widgets/yasb/systray.py
- src/core/widgets/yasb/systray.py
feat(systray): option to show/hide unpinned button
feat(systray): network icon filtering option
> fix(systray): properly hide pinned container on last icon delete

- docs/Styling.md
> docs: update styling wiki

- src/core/utils/glazewm/client.py
- src/core/widgets/glazewm/tiling_direction.py
- src/core/widgets/glazewm/workspaces.py
1. Only monitor handle is now a hard requirement from the data GlazeWM sends over IPC. If monitor name is not found - replace it with a placeholder.
2. Added an additional None check for GlazeWM data processing in case something like `{ "data": null }` is returned. Avoids the potential crash.
3. Workspaces widget now sets the monitor handle on `showEvent`.
4. Proper name for the tiling direction logger.
5. Tiling direction widget now subscribes to the additional event `focused_container_moved`. But it's all for naught until GlazeWM fixes its `focus changed` event (reported already).
6. Some minor code refactors.
> General fixes/improvements to GlazeWM client and widgets

- src/cli.py
Although this leads to some code duplication (like shortcut functionality and read/write messages), it improves the startup times by about 5 times. 
Most of the heavy imports are lazily imported now when they are needed.
> refactor(cli): improved startup times from 500ms to 100ms

- src/core/utils/win32/media.py
- src/core/validation/widgets/yasb/weather.py
- src/core/widgets/yasb/weather.py
- Switched from urllib to QNetworkAccessManager
- Added cache for icons and weather data
- Added retries (10 sec for weather, 5 sec for icons) in case of network errors
- Multiple widgets with the same url will not fetch the data multiple times
- If there are multiple different widgets with different urls, they will fetch data separately
- N/A will only be displayed if the initial data is missing, otherwise show the last known value
- General code cleanup and refactoring
- Removed spamming log from media widget
> refactor(weather_widget): refactored weather widget

- docs/widgets/(Widget)-Weather.md
- src/core/widgets/yasb/weather.py
Fixed the class name typo (arert -> alert).
Might break styles🤷‍♂️
> fix(weather): fix the class name typo (arert -> alert)

- src/cli.py
- src/core/bar.py
- src/core/utils/cli_server.py
- src/core/utils/controller.py
- Added `send_command_to_application` method to handle various commands.
- Updated CLI argument parsing to support new commands: show-bar, hide-bar, and toggle-bar.
- Integrated event service to manage bar visibility based on CLI commands.
- Enhanced CLI server to recognize and process new commands.
> feat(cli): implement command handling for show, hide, and toggle bar

- src/core/widgets/yasb/github.py
For me the notification dot was only visible on the alt_label and didn't update when i read a notification. This PR fixes these issues.
> fix(github): fix `notification dot` visibility on all labels

- src/core/validation/widgets/glazewm/workspaces.py
- src/core/widgets/glazewm/workspaces.py
When hovering over the workspaces widget, scrolling with mouse wheel will scroll through the workspaces.
> feat(glazewm): scroll through workspaces

- src/core/utils/komorebi/client.py
https://github.com/user-attachments/assets/13f3f4ba-ff6e-43ec-91a6-10ca796aa906
> fix(komorebi_stack): correct monocle layout title

- README.md
- docs/_Sidebar.md
- docs/widgets/(Widget)-Grouper.md
- src/build.py
- src/core/validation/widgets/yasb/grouper.py
- src/core/widgets/yasb/grouper.py
This PR implements a new widget to group other widgets together for styling purposes.
> feat(grouper): add new widget to group widgets together for styling

- src/core/widgets/yasb/language.py
Will return focus to the original window when the language popup is used to change the language.
Important when "Let me use a different input method for each app window" option is enabled in Windows settings.
Without this change it will not change the language of the target app, just the YASB itself.
> feat(language_popup): return focus on popup language change

- docs/Styling.md
- src/core/utils/tooltip.py
- src/core/utils/widgets/systray/systray_widget.py
- src/core/widgets/yasb/bluetooth.py
- src/core/widgets/yasb/brightness.py
- src/core/widgets/yasb/clock.py
- src/core/widgets/yasb/github.py
- src/core/widgets/yasb/microphone.py
- src/core/widgets/yasb/recycle_bin.py
- src/core/widgets/yasb/server_monitor.py
- src/core/widgets/yasb/taskbar.py
- src/core/widgets/yasb/todo.py
- src/core/widgets/yasb/traffic.py
- src/core/widgets/yasb/update_check.py
- src/core/widgets/yasb/volume.py
- src/core/widgets/yasb/wallpapers.py
- src/styles.css
- Added a new CustomToolTip class for enhanced tooltip functionality.
- Integrated fade-in and fade-out animations for better user experience.
- Implemented TooltipEventFilter to manage tooltip visibility based on mouse events.
- Provided a set_tooltip function for easy tooltip assignment to widgets.
> feat(tooltip): implement custom tooltip

- docs/widgets/(Widget)-Weather.md
- src/core/utils/widgets/weather/api.py
- src/core/utils/widgets/weather/widgets.py
- src/core/validation/widgets/yasb/weather.py
- src/core/widgets/yasb/weather.py
- Moved api related functionality to `utils/widgets/weather/api.py`.
- Moved widgets related functionality to `utils/widgets/weather/widgets.py`.
- Weather card will now show scrollable hourly weather data for each day.
- Daily weather widgets are now clickable and will switch the hourly view.
- Additional styling is available for weather-card-day class: `.active`.
- Curve color can be changed in CSS using `background-color` style for `.weather-card .hourly-data` class.
- Text color can be changed in CSS using `color` style for `.weather-card .hourly-data` class.
- Added `.weather-card .hourly-data` class to style the hourly data scrollable container.
- Added optional min/max tooltip for weather widget.
New options for config.yaml `weather_card`
New options for weather_card:
```yaml …
```
> feat(weather_hourly): added weather card hourly view

- src/core/utils/widgets/komorebi/animation.py
- src/core/widgets/komorebi/workspaces.py
- Introduced KomorebiAnimation class for managing width animations.
- Implemented methods to lock width, animate width changes, and handle state transitions.
- Updated WorkspaceButton to utilize the new animation methods for smoother UI transitions.
> feat(animation): add centralized width animation for workspace buttons

- docs/widgets/(Widget)-Grouper.md
- src/core/validation/widgets/yasb/grouper.py
- src/core/widgets/yasb/grouper.py
- src/core/widgets/yasb/media.py
- Introduced `hide_empty` boolean option to control visibility of the grouper widget when all child widgets are hidden.
- Enhanced widget behavior to automatically hide or show based on child widget visibility.
> feat(grouper): add hide_empty option to GrouperWidget
